package com.example.hcrunning.app;

import android.app.Activity;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.ToggleButton;

import java.util.ArrayList;
import java.util.List;


/**
 * A simple {@link Fragment} subclass.
 */
public class RunFragment extends Fragment implements View.OnClickListener {
  // TODO: Rename parameter arguments, choose names that match
  // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
  private static final String ARG_PARAM1 = "param1";
  private static final String ARG_PARAM2 = "param2";

  // TODO: Rename and change types of parameters
  private String mParam1;
  private String mParam2;

//  private OnFragmentInteractionListener mListener;

  //! The text view that displays the current interval countdown time in the display
  private TextView mCurrentDisplayTimeTextView;

  //! The interval processes that mangages the intervals being run
  private IntervalProcessor mTimeProcessor;

  //! List of intervals used within the interval processor
  private List<TimeInterval> mIntervals;

  //! The adapter that manages the time intervals in the display for the list view
  private HCRunningArrayAdapter mAdapter;

  //! The list view that displays the intervals while the processor runs
  private ListView mListView;


  /**
   * Use this factory method to create a new instance of this fragment using the provided parameters.
   *
   * @param param1 Parameter 1.
   * @param param2 Parameter 2.
   * @return A new instance of fragment RunFragment.
   */
  // TODO: Rename and change types and number of parameters
  public static RunFragment newInstance(String param1, String param2) {
    RunFragment fragment = new RunFragment();
    Bundle args = new Bundle();
    args.putString(ARG_PARAM1, param1);
    args.putString(ARG_PARAM2, param2);
    fragment.setArguments(args);
    return fragment;
  }

  public RunFragment() {
  }

  @Override
  public void onAttach(Activity activity) {
    super.onAttach(activity);
  }

  @Override
  public void onDetach() {
    super.onDetach();
  }

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    if (getArguments() != null) {
      mParam1 = getArguments().getString(ARG_PARAM1);
      mParam2 = getArguments().getString(ARG_PARAM2);
    }

    this.mTimeProcessor = new IntervalProcessor( this.mCurrentDisplayTimeTextView, getActivity().getApplicationContext() );
    mAdapter = new HCRunningArrayAdapter(getActivity().getApplicationContext(), new ArrayList<TextView>(), getActivity());
  }

  @Override
  public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

    View view = inflater.inflate(R.layout.fragment_run, container, false);
    this.mCurrentDisplayTimeTextView = (TextView)view.findViewById(R.id.textview_curent_countdown);
    this.mListView = (ListView)view.findViewById(R.id.listview_countdown_display);
    mListView.setAdapter(mAdapter);

    ToggleButton startButton = (ToggleButton) view.findViewById(R.id.button_start);
    startButton.setOnClickListener(this);

    ToggleButton pauseButton = (ToggleButton) view.findViewById(R.id.button_pause);
    pauseButton.setOnClickListener(this);

    Button resetButton = (Button) view.findViewById(R.id.button_reset);
    resetButton.setOnClickListener(this);

    return view;
  }

  //region AutoGenerated Overloaded Methods
  // TODO: Rename method, update argument and hook method into UI event
//
//  /**
//   * This interface must be implemented by activities that contain this
//   * fragment to allow an interaction in this fragment to be communicated
//   * to the activity and potentially other fragments contained in that
//   * activity.
//   * <p/>
//   * See the Android Training lesson <a href=
//   * "http://developer.android.com/training/basics/fragments/communicating.html"
//   * >Communicating with Other Fragments</a> for more information.
//   */
//  public interface OnFragmentInteractionListener {
//    // TODO: Update argument type and name
//    public void onFragmentInteraction(Uri uri);
//  }
  //endregion

  public void onStartAndCancelToggleButton(View view) {
    ToggleButton pauseContinueButtonActivator = (ToggleButton) view.findViewById(R.id.button_pause);
  //! \todo Disabled adding once the clock started ticking.  Make it so they cannot change until it is stopped?
  //  Button addButtonActivator = (Button) view.findViewById(R.id.addButton);

    boolean start = ((ToggleButton) view).isChecked();
    if (!start) {
      // Action when "Cancel" is pressed
      pauseContinueButtonActivator.setEnabled(false);
   //   addButtonActivator.setEnabled(true);
      this.mTimeProcessor.stop();
//        this.mAdapter.clear();
//        this.mAdapter.notifyDataSetChanged();
//        this.mIntervals.clear();         // or this.mAdapter.clearListItem();
    } else {
      // Action when "Start" is pressed
      pauseContinueButtonActivator.setEnabled(true);
   //   addButtonActivator.setEnabled(false);
        /* pull list of times to count down
         * foreach one in the list set the time on the count down timer
         * ding at end, then pull do next time
         */
      this.mIntervals = mAdapter.getTimes();
      this.mTimeProcessor.setIntervals(mIntervals);
      this.mTimeProcessor.start();
    }
  }

  public void onPauseAndContinueToggleButton(View view) {
    boolean pause = ((ToggleButton) view).isChecked();
    if (!pause) {
      // Action when "Continue" is pressed
      this.mTimeProcessor.start();
    } else {
      // Action when "Pause" is pressed
      this.mTimeProcessor.pause();
    }
  }


  public void onResetButton(View view) {
    this.mTimeProcessor.cancel();
    this.mAdapter.clear();
    this.mAdapter.clearListItem();
    this.mAdapter.notifyDataSetChanged();
    //this.mIntervals.clear();
  }

  @Override
  public void onClick(View v) {
    switch (v.getId()) {
      case R.id.button_start:
        onStartAndCancelToggleButton(v);
        break;
      case R.id.button_pause:
        onPauseAndContinueToggleButton(v);
        break;
      case R.id.button_reset:
        onResetButton(v);
        break;
    }
  }
}
